class Encoding:
    @property
    def ids(self) -> list[int]: ...
    @property
    def offsets(self) -> list[tuple[int, int]]: ...

class Tokenizer:
    @staticmethod
    def from_file(path: str) -> Tokenizer: ...
    def no_padding(self) -> None: ...
    def no_truncation(self) -> None: ...
    def encode(self, sequence: str, *, add_special_tokens: bool = True) -> Encoding: ...
